arlas:
  demo:
    allow_delete: false
    authorization: null
    elastic: null
    server:
      headers:
        Content-Type: application/json
      location: https://demo.cloud.arlas.io/arlas/server
  local:
    allow_delete: true
    authorization: null
    elastic:
      headers:
        Content-Type: application/json
      location: http://localhost:9200
    server:
      headers:
        Content-Type: application/json
      location: http://localhost:9999/arlas
mappings:
  arlas_eo:
    headers: null
    location: https://raw.githubusercontent.com/gisaia/ARLAS-EO/master/mapping.json
models:
  arlas_eo:
    headers: null
    location: https://raw.githubusercontent.com/gisaia/ARLAS-EO/master/collection.json
