site_name: ARLAS Command Line (arlas_cli)
site_url: "https://gisaia.github.io/arlas_cli"
site_author: Gisaïa - SCALING GEOSPATIAL INTELLIGENCE
site_description: Documentation for the arlas_cli command line

# Repository
repo_name: gisaia/arlas_cli
repo_url: https://github.com/gisaia/arlas_cli
edit_uri: ""

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details

theme:
  name: material
  highlightjs: true
  palette:
    primary: 'pink'
    accent: 'light-blue'

nav:
- About arlas_cli: index.md
- Getting started: started.md
- Installation: install.md
- Configuration: configuration.md
- Commands:
  - Getting help: help.md
  - confs: confs.md
  - indices: indices.md
  - collections: collections.md
  - persist: persist.md
  - iam: iam.md
- Concepts: concepts.md

plugins:
  - search
  - termynal:
      prompt_literal_start:
        - ">"