name: Test arlas_cli

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: scripts/tests.sh
